apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: blog-websites

images:
  - name: ghcr.io/liaosirui/website-github-actions
    newTag: sha-409246a3
